### ISSUE TITLE
Error loading script: clean_up_tab.py

### ISSUE THREAD

**Issue by kotaxyz** [novitalabs/sd-webui-cleaner#10]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4

i get this error and the extension dosnt show in the webui

*** Error loading script: clean_up_tab.py
    Traceback (most recent call last):
      File "I:\stable-diffusion-webui\modules\scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "I:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "I:\stable-diffusion-webui\extensions\sd-webui-cleaner\scripts\clean_up_tab.py", line 7, in <module>
        from modules.ui_components import ToolButton, ResizeHandleRow
    ImportError: cannot import name 'ResizeHandleRow' from 'modules.ui_components' (I:\stable-diffusion-webui\modules\ui_components.py)

**Comment by xiaoshun111** [comment]
This error also occurs in mine. Have you solved it

**Comment by kotaxyz** [comment]
> This error also occurs in mine. Have you solved it

it seems i deleted it i can't find it in my extension folder , i use this https://github.com/Uminosachi/sd-webui-inpaint-anything it has more functions and also the cleaner and works for me , test it and if you have any issues tell me
