### ISSUE TITLE
cleaner just stoped working today on Forge

### ISSUE THREAD

**Issue by ali0une** [novitalabs/sd-webui-cleaner#12]
Hi there.

cleaner just stoped working today on [Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge).

Here is the error :
```
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/whatever/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/whatever/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/whatever/stable-diffusion-webui-forge/extensions/sd-webui-cleaner/scripts/api.py", line 7, in <module>
        from scripts import lama
    ImportError: cannot import name 'lama' from 'scripts' (/home/iman/compil/A1111/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: clean_up_tab.py
    Traceback (most recent call last):
      File "/whatever/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/whatever/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/whatever/stable-diffusion-webui-forge/extensions/sd-webui-cleaner/scripts/clean_up_tab.py", line 11, in <module>
        from scripts import lama
    ImportError: cannot import name 'lama' from 'scripts' (/home/iman/compil/A1111/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/scripts/__init__.py)
```

**Comment by ali0une** [comment]
relevant issue and fix https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/716#issuecomment-2291150487

**Comment by ali0une** [comment]
As it's a [Forge related issue](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1134#issuecomment-2290925628) that is now fixed i think we can close this one.
