### ISSUE TITLE
sd-webui 1.5 is not supported

### ISSUE THREAD

**Issue by luliloveshe918** [novitalabs/sd-webui-cleaner#13]
I am using sd-webui version 1.5. After downloading the cleaner plugin, I start sd-webui and get an error message, as follows:
I checked the changelog of sd-webui and found that ResizeHandleRow appeared in version 1.8
How can I make the cleaner plugin support sd-webui version 1.5?

2024-11-01 17:56:51 - ***
2024-11-01 17:56:51 - Error loading script: clean_up_tab.py
2024-11-01 17:56:51 -     Traceback (most recent call last):
      File "E:\develop\python\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\develop\python\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\develop\python\stable-diffusion-webui\extensions\sd-webui-cleaner\scripts\clean_up_tab.py", line 7, in <module>
        from modules.ui_components import ToolButton, ResizeHandleRow
    ImportError: cannot import name 'ResizeHandleRow' from 'modules.ui_components' (E:\develop\python\stable-diffusion-webui\modules\ui_components.py)

**Comment by athor** [comment]
Old but still: no errors for me
As of today working great on SD 1.5 up to date version
thanks dev
